/**
 * Downloads the Latin subsets of the site's two open-licensed families and
 * writes a local @font-face stylesheet, so the production build carries no
 * third-party font requests.
 *
 * Usage: node scripts/fetch-fonts.mjs
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'src', 'assets', 'fonts');
mkdirSync(OUT, { recursive: true });

const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  { name: 'Inter', spec: 'Inter:wght@400;500;600;700' },
  { name: 'Archivo', spec: 'Archivo:wght@600;700' },
];

// Latin and Latin Extended cover English and Spanish, including ñ, accents,
// and the inverted punctuation Spanish needs.
const WANTED = new Set(['latin', 'latin-ext']);

const blocks = [];

for (const family of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family.spec)}&display=swap`;
  const css = await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => r.text());

  // The API emits "/* subset */" immediately before each @font-face rule.
  const chunks = css.split('/*').slice(1);
  for (const chunk of chunks) {
    const subset = chunk.slice(0, chunk.indexOf('*/')).trim();
    if (!WANTED.has(subset)) continue;

    const rule = chunk.slice(chunk.indexOf('*/') + 2);
    const weight = /font-weight:\s*(\d+)/.exec(rule)?.[1];
    const src = /url\((https:[^)]+\.woff2)\)/.exec(rule)?.[1];
    const range = /unicode-range:\s*([^;]+);/.exec(rule)?.[1]?.trim();
    if (!weight || !src) continue;

    const file = `${family.name.toLowerCase()}-${weight}-${subset}.woff2`;
    const bytes = Buffer.from(await fetch(src, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()));
    writeFileSync(join(OUT, file), bytes);

    blocks.push(
      `@font-face {\n` +
        `  font-family: '${family.name}';\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        `  src: url('../fonts/${file}') format('woff2');\n` +
        (range ? `  unicode-range: ${range};\n` : '') +
        `}`
    );
    console.log(`  ${file}  ${(bytes.length / 1024).toFixed(1)} KB`);
  }
}

writeFileSync(
  join(ROOT, 'src', 'styles', 'fonts.css'),
  `/* Generated by scripts/fetch-fonts.mjs. Inter and Archivo are licensed under the SIL Open Font License 1.1. */\n\n` +
    blocks.join('\n\n') +
    '\n'
);

console.log(`\n${blocks.length} faces bundled.`);
