# Generated by tools/process-about-hero.py. Do not edit by hand.
ABOUT_DIMS = {
    "about-facility-desktop": (1672, 941),
    "about-facility-mobile": (941, 1672),
}

# The tiers actually written. A source is never upscaled, so this is what
# the srcset may list.
ABOUT_TIERS = {
    "about-facility-desktop": (800, 1200, 1672),
    "about-facility-mobile": (360, 540, 720, 941),
}
