#!/usr/bin/env python3
"""Download the self-hosted NATFISH webfonts.

Bitter (display) and Source Sans 3 (body) are both SIL Open Font License 1.1,
so serving them from our own origin is permitted. Self-hosting also means the
site keeps working with no third-party request, which matters for a demo on
unreliable connections.

Only the latin and latin-ext subsets are kept: the site is English, and the
cyrillic/greek/vietnamese subsets would triple the payload for nothing. Google
serves these as variable fonts, so one file per subset covers weights 400-700.

Run from the natfish/ folder:
    python3 tools/fetch-fonts.py
"""
import pathlib
import re
import urllib.request

OUT = pathlib.Path(__file__).resolve().parent.parent / "assets" / "fonts"

API = (
    "https://fonts.googleapis.com/css2"
    "?family=Bitter:wght@400..700"
    "&family=Source+Sans+3:wght@400..700"
    "&display=swap"
)

# A modern UA is required or the API serves legacy TTF instead of WOFF2.
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

KEEP = {"latin", "latin-ext"}

FACE_RE = re.compile(
    r"/\*\s*([\w-]+)\s*\*/\s*@font-face\s*\{(.*?)\}", re.S
)


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def field(block, name):
    m = re.search(name + r":\s*([^;]+);", block)
    return m.group(1).strip() if m else None


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    css = get(API).decode()

    faces = []
    for subset, block in FACE_RE.findall(css):
        if subset not in KEEP:
            continue
        family = field(block, "font-family").strip("'\"")
        weight = field(block, "font-weight")
        urange = field(block, "unicode-range")
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)

        slug = family.lower().replace(" ", "-")
        name = f"{slug}-{subset}.woff2"
        (OUT / name).write_bytes(get(url))
        faces.append((family, weight, urange, name))
        print(f"  {name:34} {(OUT / name).stat().st_size / 1024:6.1f} KB")

    rules = []
    for family, weight, urange, name in faces:
        rules.append(f"""@font-face {{
  font-family: "{family}";
  font-style: normal;
  font-weight: {weight};
  font-display: swap;
  src: url("../fonts/{name}") format("woff2");
  unicode-range: {urange};
}}""")

    header = """/* ==========================================================================
   NATFISH webfonts, self-hosted
   Bitter and Source Sans 3, SIL Open Font License 1.1. See fonts/OFL.txt.
   Variable files: one request per subset covers weights 400-700.
   Generated by tools/fetch-fonts.py -- do not hand-edit.
   ========================================================================== */

"""
    css_out = OUT.parent / "css" / "fonts.css"
    css_out.write_text(header + "\n\n".join(rules) + "\n")
    print(f"\n{css_out.relative_to(OUT.parent.parent)}: {len(faces)} faces")

    (OUT / "OFL.txt").write_text(
        "Bitter and Source Sans 3 are licensed under the SIL Open Font "
        "License, Version 1.1.\n"
        "Bitter: https://github.com/solmatas/BitterPro\n"
        "Source Sans 3: https://github.com/adobe-fonts/source-sans\n"
        "Full licence: https://openfontlicense.org\n"
    )


if __name__ == "__main__":
    main()
