# Generated by tools/process-gallery-images.py and
# tools/process-gallery-additions.py. Do not edit by hand.
GALLERY_DIMS = {
    "01-lobster-fisher-boat-catch": (1400, 1050),
    "02-lobster-harvest-boat": (1400, 1050),
    "03-belizean-pride-frozen-lobster-10kg": (1400, 1050),
    "04-belizean-pride-lobster-head-meat": (1400, 1050),
    "05-frozen-fish-fillets-box": (1400, 1050),
    "06-frozen-fish-portions-box": (1400, 1050),
    "07-belizean-pride-exhibition-display": (1400, 1050),
    "08-natfish-delegation-black-uniforms": (1400, 1050),
    "09-natfish-delegation-white-uniforms": (1400, 1050),
    "10-natfish-team-group": (1400, 1050),
    "coastal-fishing-structures": (1400, 646),
    "fisherman-spiny-lobster": (1200, 1600),
    "fisherman-two-spiny-lobsters": (720, 960),
    "lionfish-fillets-4x3": (1400, 1050),
    "natfish-food-taipei-2026": (1280, 720),
    "natfish-workshop": (1280, 720),
    "natfish-workshop-group": (1280, 720),
}

# stem -> classification, from the client's folders and brief.
GALLERY_GROUPS = {
    "01-lobster-fisher-boat-catch": "fishing",
    "02-lobster-harvest-boat": "fishing",
    "03-belizean-pride-frozen-lobster-10kg": "products",
    "04-belizean-pride-lobster-head-meat": "products",
    "05-frozen-fish-fillets-box": "products",
    "06-frozen-fish-portions-box": "products",
    "07-belizean-pride-exhibition-display": "trade",
    "08-natfish-delegation-black-uniforms": "trade",
    "09-natfish-delegation-white-uniforms": "trade",
    "10-natfish-team-group": "trade",
    "coastal-fishing-structures": "fishing",
    "fisherman-spiny-lobster": "fishing",
    "fisherman-two-spiny-lobsters": "fishing",
    "lionfish-fillets-4x3": "products",
    "natfish-food-taipei-2026": "trade",
    "natfish-workshop": "training",
    "natfish-workshop-group": "training",
}

# stem -> the widths actually written, so no srcset names a
# derivative that does not exist.
GALLERY_TIERS = {
    "01-lobster-fisher-boat-catch": (480, 800, 1400),
    "02-lobster-harvest-boat": (480, 800, 1400),
    "03-belizean-pride-frozen-lobster-10kg": (480, 800, 1400),
    "04-belizean-pride-lobster-head-meat": (480, 800, 1400),
    "05-frozen-fish-fillets-box": (480, 800, 1400),
    "06-frozen-fish-portions-box": (480, 800, 1400),
    "07-belizean-pride-exhibition-display": (480, 800, 1400),
    "08-natfish-delegation-black-uniforms": (480, 800, 1400),
    "09-natfish-delegation-white-uniforms": (480, 800, 1400),
    "10-natfish-team-group": (480, 800, 1400),
    "coastal-fishing-structures": (480, 800, 1400),
    "fisherman-spiny-lobster": (480, 800, 1200),
    "fisherman-two-spiny-lobsters": (480, 720),
    "lionfish-fillets-4x3": (480, 800, 1400),
    "natfish-food-taipei-2026": (480, 800, 1280),
    "natfish-workshop": (480, 800, 1280),
    "natfish-workshop-group": (480, 800, 1280),
}
