# Generated by tools/process-gallery-images.py. Do not edit by hand.
GALLERY_DIMS = {
    "01-lobster-fisher-boat-catch": (1400, 1050),
    "02-lobster-harvest-boat": (1400, 1050),
    "03-belizean-pride-frozen-lobster-10kg": (1400, 1050),
    "04-belizean-pride-lobster-head-meat": (1400, 1050),
    "05-frozen-fish-fillets-box": (1400, 1050),
    "06-frozen-fish-portions-box": (1400, 1050),
    "07-belizean-pride-exhibition-display": (1400, 1050),
    "08-natfish-delegation-black-uniforms": (1400, 1050),
    "09-natfish-delegation-white-uniforms": (1400, 1050),
    "10-natfish-team-group": (1400, 1050),
}

# stem -> classification, taken from the client's folder names.
GALLERY_GROUPS = {
    "01-lobster-fisher-boat-catch": "fishing",
    "02-lobster-harvest-boat": "fishing",
    "03-belizean-pride-frozen-lobster-10kg": "products",
    "04-belizean-pride-lobster-head-meat": "products",
    "05-frozen-fish-fillets-box": "products",
    "06-frozen-fish-portions-box": "products",
    "07-belizean-pride-exhibition-display": "trade",
    "08-natfish-delegation-black-uniforms": "trade",
    "09-natfish-delegation-white-uniforms": "trade",
    "10-natfish-team-group": "trade",
}
