# Generated by tools/process-hero-images.py. Do not edit by hand.
HERO_DIMS = {
    "hero-1-fisher-with-conch-catch": (1400, 787),
    "hero-2-boat-leaving-harbour": (1400, 787),
    "hero-3-fishers-at-sunrise": (1400, 787),
}
