# Generated by tools/process-hero-images.py. Do not edit by hand.
HERO_DIMS = {
    "hero-lobster-diver-dock-desktop": (2400, 1080),
    "hero-lobster-diver-dock-mobile": (1080, 1920),
    "hero-lobster-boat-catch-desktop": (2400, 1080),
    "hero-lobster-boat-catch-mobile": (1080, 1920),
    "hero-2-boat-leaving-harbour": (1400, 787),
}
