#!/usr/bin/env python3
"""Emit assets/js/natfish-strings.js from the Spanish dictionary.

Only strings that actually appear in the built pages are shipped, plus the
handful the season script composes at runtime. Anything without a translation
is reported and simply stays English in the browser.

    python3 tools/i18n-build.py
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

from natfish_es import ES  # noqa: E402

import importlib.util  # noqa: E402
spec = importlib.util.spec_from_file_location(
    "extract", ROOT / "tools" / "i18n-extract.py")
extract = importlib.util.module_from_spec(spec)
spec.loader.exec_module(extract)

# Strings the scripts build at runtime rather than reading from markup. The
# extractor only sees the built HTML, so anything a script creates after load
# has to be listed here or it ships untranslated.
RUNTIME = [
    # natfish-seasons.js
    "Within the standard regulatory season",
    "Standard closed period",
    "Subject to national quota and current Fisheries notices",
    # natfish-ai.js: the chrome around the Chatbase panel, which is built on
    # first open and therefore exists in no page.
    "Close NATFISH AI",
    "NATFISH AI chat",
    "NATFISH AI is open.",
    # ... and the note shown in the artifact preview, where the embed's host
    # is blocked by the artifact CSP.
    "NATFISH AI is live on the website itself.",
    "This shareable preview is a single file and cannot load the chat window. "
    "Open the deployed site to talk to NATFISH AI.",
]


def main():
    used = set(extract.collect()) | set(RUNTIME)
    es = {k: ES[k] for k in sorted(used) if k in ES}
    missing = sorted(k for k in used if k not in ES)
    assert_no_literal_escapes(es)

    payload = json.dumps({"es": es}, ensure_ascii=False, indent=1,
                         sort_keys=True)

    out = ROOT / "assets" / "js" / "natfish-strings.js"
    out.write_text(
        "/* ==========================================================================\n"
        "   NATFISH Spanish strings\n"
        "   Generated by tools/i18n-build.py from tools/natfish_es.py. Do not edit.\n"
        "\n"
        "   CONCEPT-STAGE TRANSLATION: this Spanish should receive a final review from\n"
        "   a Belizean Spanish speaker designated by NATFISH before public launch.\n"
        "   Keys are the English source strings, so a missing entry falls back to\n"
        "   English rather than rendering blank.\n"
        "   ========================================================================== */\n"
        "window.NATFISH_STRINGS = " + payload + ";\n",
        encoding="utf-8",
    )

    print(f"{out.relative_to(ROOT)}: {len(es)} Spanish strings, "
          f"{len(missing)} missing")
    for m in missing:
        print("  MISSING:", m)
    return 1 if missing else 0



def assert_no_literal_escapes(strings):
    """A Spanish value must never contain a literal \\uXXXX or \\xXX sequence.

    These blocks are written through shell heredocs, where a doubled backslash
    survives into the Python source and Python then reads it as an escaped
    backslash rather than the character it names. The result ships to the
    browser as the text "\\u00f3" where an "o with an accent" was meant. It
    happened once across 102 strings and was invisible until someone read the
    Spanish site, so it is checked rather than remembered.
    """
    import re as _re
    bad = [k for k, v in strings.items()
           if _re.search(r"\\[ux][0-9a-fA-F]{2}", v)]
    if bad:
        print(f"  !! {len(bad)} Spanish string(s) carry a literal escape sequence")
        for k in bad[:5]:
            print(f"     {k[:70]}")
        raise SystemExit(1)


if __name__ == "__main__":
    raise SystemExit(main())
