#!/usr/bin/env python3
"""Emit assets/js/natfish-strings.js from the Spanish dictionary.

Only strings that actually appear in the built pages are shipped, plus the
handful the season script composes at runtime. Anything without a translation
is reported and simply stays English in the browser.

    python3 tools/i18n-build.py
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

from natfish_es import ES  # noqa: E402

import importlib.util  # noqa: E402
spec = importlib.util.spec_from_file_location(
    "extract", ROOT / "tools" / "i18n-extract.py")
extract = importlib.util.module_from_spec(spec)
spec.loader.exec_module(extract)

# Strings the season script builds at runtime rather than reading from markup.
RUNTIME = [
    "Within the standard regulatory season",
    "Standard closed period",
    "Subject to national quota and current Fisheries notices",
]


def main():
    used = set(extract.collect()) | set(RUNTIME)
    es = {k: ES[k] for k in sorted(used) if k in ES}
    missing = sorted(k for k in used if k not in ES)

    payload = json.dumps({"es": es}, ensure_ascii=False, indent=1,
                         sort_keys=True)

    out = ROOT / "assets" / "js" / "natfish-strings.js"
    out.write_text(
        "/* ==========================================================================\n"
        "   NATFISH Spanish strings\n"
        "   Generated by tools/i18n-build.py from tools/natfish_es.py. Do not edit.\n"
        "\n"
        "   CONCEPT-STAGE TRANSLATION: this Spanish should receive a final review from\n"
        "   a Belizean Spanish speaker designated by NATFISH before public launch.\n"
        "   Keys are the English source strings, so a missing entry falls back to\n"
        "   English rather than rendering blank.\n"
        "   ========================================================================== */\n"
        "window.NATFISH_STRINGS = " + payload + ";\n",
        encoding="utf-8",
    )

    print(f"{out.relative_to(ROOT)}: {len(es)} Spanish strings, "
          f"{len(missing)} missing")
    for m in missing:
        print("  MISSING:", m)
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
