#!/usr/bin/env python3
"""Build the web derivatives for the gallery photographs added after the
original supplied set.

The first ten arrived sorted into three folders that carried their own
classification, which is why tools/process-gallery-images.py reads folder
names. This second delivery is a flat folder of seven files whose
classification came in the brief's own table instead, so it is declared here,
next to the filenames it describes.

Unlike the first set these are not all 4:3: there is a 2.17 panorama, two 0.75
portraits and three 16:9 frames. Nothing is cropped here. The files keep their
full frames, and the page holds them in a 4:3 card with a per-image
`object-position` so the fisher, the lobster and the group all stay in shot -
while the lightbox still opens the whole photograph.

Derivatives are named by their REAL pixel width rather than by a nominal tier.
A 720px-wide source has no honest "1400w" version, and a srcset that claims one
either 404s or lies to the browser's density calculation. GALLERY_TIERS records
what was actually written so the markup can only name files that exist.

Existing entries in tools/gallery_dims.py are merged, never replaced, so this
can run without the first set's source folders being present.

Usage:
    python3 tools/process-gallery-additions.py <dir containing the 7 files>
"""
import pathlib
import sys

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "img" / "gallery"

# The widest a gallery figure is ever asked to render: one column of a
# three-column grid on a 1440 desktop, at 2x. Sources narrower than a tier are
# never upscaled - the tier is simply dropped.
TIERS = (480, 800, 1400)

# stem -> classification key. Taken from the brief's table: Products,
# Fisheries, Events and Training, mapped onto the gallery's own filter groups.
# "Training" is a fourth group rather than a squeeze into "Trade Shows &
# Representation", because a workshop is not a trade show.
GROUPS = {
    "lionfish-fillets-4x3": "products",
    "fisherman-two-spiny-lobsters": "fishing",
    "coastal-fishing-structures": "fishing",
    "fisherman-spiny-lobster": "fishing",
    "natfish-food-taipei-2026": "trade",
    "natfish-workshop": "training",
    "natfish-workshop-group": "training",
}

SOURCE_EXTS = (".jpeg", ".jpg", ".png", ".webp")


def strip(im):
    """Return the pixels with no EXIF, ICC or other carried-over metadata."""
    clean = Image.new(im.mode, im.size)
    clean.putdata(list(im.getdata()))
    return clean


def load_existing():
    """Whatever tools/gallery_dims.py already holds, so a run only ever adds."""
    sys.path.insert(0, str(ROOT / "tools"))
    try:
        import gallery_dims as g
        return (dict(g.GALLERY_DIMS), dict(g.GALLERY_GROUPS),
                dict(getattr(g, "GALLERY_TIERS", {})))
    except ImportError:
        return {}, {}, {}


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    src = pathlib.Path(sys.argv[1])
    if not src.is_dir():
        raise SystemExit(f"ERROR: {src} is not a directory")
    OUT.mkdir(parents=True, exist_ok=True)

    dims, groups, tiers_by_stem = load_existing()
    # The first ten predate per-stem tiers and are all 1600 wide, so every one
    # of them really does have all three.
    for stem in groups:
        tiers_by_stem.setdefault(stem, list(TIERS))

    found = {}
    for path in sorted(src.iterdir()):
        if path.suffix.lower() in SOURCE_EXTS and path.stem in GROUPS:
            found[path.stem] = path
    missing = sorted(set(GROUPS) - set(found))
    if missing:
        raise SystemExit("ERROR: missing source file(s): " + ", ".join(missing))

    for stem, path in sorted(found.items()):
        im = strip(Image.open(path).convert("RGB"))
        written = []
        for tier in TIERS:
            # Never upscale, and never write two files with the same pixels
            # under two names.
            width = min(tier, im.width)
            if width in written:
                continue
            size = (width, round(im.height * width / im.width))
            r = im.resize(size, Image.LANCZOS) if size != im.size else im
            r.save(OUT / f"{stem}-{width}.webp", "WEBP", quality=82, method=6)
            r.save(OUT / f"{stem}-{width}.jpg", "JPEG", quality=84,
                   optimize=True, progressive=True)
            written.append(width)
        big = written[-1]
        dims[stem] = (big, round(im.height * big / im.width))
        groups[stem] = GROUPS[stem]
        tiers_by_stem[stem] = written
        print(f"  {GROUPS[stem]:9s} {stem:32s} {im.width}x{im.height}"
              f"  ->  {', '.join(str(w) for w in written)}")

    lines = [
        "# Generated by tools/process-gallery-images.py and",
        "# tools/process-gallery-additions.py. Do not edit by hand.",
        "GALLERY_DIMS = {",
    ]
    for stem in sorted(dims):
        w, h = dims[stem]
        lines.append(f'    "{stem}": ({w}, {h}),')
    lines += ["}", "",
              "# stem -> classification, from the client's folders and brief.",
              "GALLERY_GROUPS = {"]
    for stem in sorted(groups):
        lines.append(f'    "{stem}": "{groups[stem]}",')
    lines += ["}", "",
              "# stem -> the widths actually written, so no srcset names a",
              "# derivative that does not exist.",
              "GALLERY_TIERS = {"]
    for stem in sorted(tiers_by_stem):
        widths = ", ".join(str(w) for w in tiers_by_stem[stem])
        lines.append(f'    "{stem}": ({widths}),')
    lines.append("}")
    (ROOT / "tools" / "gallery_dims.py").write_text("\n".join(lines) + "\n",
                                                    encoding="utf-8")

    total = sum(f.stat().st_size for f in OUT.iterdir() if f.is_file())
    print(f"\n{len(found)} added, {len(dims)} gallery images in total, "
          f"{total / 1024 / 1024:.2f} MB")


if __name__ == "__main__":
    main()
