#!/usr/bin/env python3
"""Build the web derivatives for the client's supplied gallery set.

Ten photographs the client delivered already standardised to 1600x1200, sorted
into three folders that carry the classification: fishing and harvest, products
and processing, trade shows and representation. The folder names come from the
client's own instruction file and are the source of truth for which group each
photograph belongs to.

They keep the client's filenames exactly, and they land in their own
assets/img/gallery/ folder rather than official/. Two reasons, both practical:
the supplied names collide numerically with the existing official/ set
(`01-...` twice), and `img_dir()` routes anything containing "belizean-pride"
to products/, which holds recreations from an old pamphlet. These are neither -
they are the client's own photographs of their own product - so a separate
folder keeps that distinction legible in the path.

Nothing is recoloured, retouched or re-cropped. The client standardised the
frames themselves, including the blurred fill on the images whose originals
were not 4:3, and their framing is what ships. The only operations here are
downscaling to web tiers and stripping metadata.

Usage:
    python3 tools/process-gallery-images.py <unzipped natfish-gallery dir>
"""
import pathlib
import sys

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "img" / "gallery"

# A gallery figure is one column of a 1-2-3 column layout: about 30vw on a
# desktop, so 1400w covers a retina 1440 comfortably and 1600 would be waste.
TIERS = (480, 800, 1400)

# Source folder -> the classification key used in the page and the filter.
GROUPS = {
    "01-fishing-and-harvest": "fishing",
    "02-products-and-processing": "products",
    "03-trade-shows-and-representation": "trade",
}


def strip(im):
    """Return the pixels with no EXIF, ICC or other carried-over metadata."""
    clean = Image.new(im.mode, im.size)
    clean.putdata(list(im.getdata()))
    return clean


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    src = pathlib.Path(sys.argv[1])
    OUT.mkdir(parents=True, exist_ok=True)

    dims, groups = {}, {}
    for folder, key in GROUPS.items():
        directory = src / folder
        if not directory.is_dir():
            raise SystemExit(f"ERROR: missing source folder {directory}")
        for path in sorted(directory.glob("*.jpg")):
            stem = path.stem
            im = strip(Image.open(path).convert("RGB"))
            written = []
            for tier in TIERS:
                width = min(tier, im.width)
                size = (width, round(im.height * width / im.width))
                if size in written:
                    continue
                r = im.resize(size, Image.LANCZOS)
                r.save(OUT / f"{stem}-{tier}.webp", "WEBP", quality=82, method=6)
                r.save(OUT / f"{stem}-{tier}.jpg", "JPEG", quality=84,
                       optimize=True, progressive=True)
                written.append(size)
            dims[stem] = written[-1]
            groups[stem] = key
            print(f"  {key:8s} {stem:42s} {im.width}x{im.height}")

    lines = ["# Generated by tools/process-gallery-images.py. Do not edit by hand.",
             "GALLERY_DIMS = {"]
    for stem, (w, h) in dims.items():
        lines.append(f'    "{stem}": ({w}, {h}),')
    lines.append("}")
    lines.append("")
    lines.append("# stem -> classification, taken from the client's folder names.")
    lines.append("GALLERY_GROUPS = {")
    for stem, key in groups.items():
        lines.append(f'    "{stem}": "{key}",')
    lines.append("}")
    (ROOT / "tools" / "gallery_dims.py").write_text("\n".join(lines) + "\n",
                                                    encoding="utf-8")

    total = sum(f.stat().st_size for f in OUT.iterdir() if f.is_file())
    print(f"\nwrote {len(dims)} gallery images, {total / 1024 / 1024:.2f} MB")


if __name__ == "__main__":
    main()
