#!/usr/bin/env python3
"""Build the web derivatives for photographs published with a news item.

These are the client's own photographs of their own people and activity, so
they sit in assets/img/official/ with the rest of it. They are kept out of
process-v2-images.py because that script regenerates the ten-photograph set the
General Manager supplied as one batch, and a news photograph arrives one at a
time.

Nothing is recoloured, retouched or re-cropped. The only operations are
downscaling to web tiers and stripping metadata.

Usage:
    python3 tools/process-news-images.py <source dir>

The source directory must contain one file per entry in NEWS below, named as
the second element of each pair.
"""
import pathlib
import sys

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
OFFICIAL = ROOT / "assets" / "img" / "official"

TIERS = (480, 800, 1400)

# (published stem, source filename)
NEWS = [
    ("news-food-taipei-2026-delegation", "IMG_1125.jpeg"),
]


def strip(im):
    """Return the pixels with no EXIF, ICC or other carried-over metadata."""
    clean = Image.new(im.mode, im.size)
    clean.putdata(list(im.getdata()))
    return clean


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    src = pathlib.Path(sys.argv[1])
    OFFICIAL.mkdir(parents=True, exist_ok=True)

    dims = {}
    for stem, filename in NEWS:
        path = src / filename
        if not path.is_file():
            raise SystemExit(f"ERROR: missing source {path}")
        im = strip(Image.open(path).convert("RGB"))
        written = []
        for tier in TIERS:
            width = min(tier, im.width)
            size = (width, round(im.height * width / im.width))
            r = im.resize(size, Image.LANCZOS)
            # The filename keeps the tier even where the source is narrower
            # than it, because picture() emits a fixed 480/800/1400 srcset.
            # The recorded dimensions below are the real ones.
            r.save(OFFICIAL / f"{stem}-{tier}.webp", "WEBP", quality=82, method=6)
            r.save(OFFICIAL / f"{stem}-{tier}.jpg", "JPEG", quality=84,
                   optimize=True, progressive=True)
            written.append(size)
        dims[stem] = written[-1]
        print(f"  {stem:38s} {im.width}x{im.height} -> "
              f"{', '.join(f'{w}x{h}' for w, h in written)}")

    lines = ["# Generated by tools/process-news-images.py. Do not edit by hand.",
             "NEWS_DIMS = {"]
    for stem, (w, h) in dims.items():
        lines.append(f'    "{stem}": ({w}, {h}),')
    lines.append("}")
    (ROOT / "tools" / "news_dims.py").write_text("\n".join(lines) + "\n",
                                                 encoding="utf-8")
    print(f"\nwrote {len(dims)} news image(s)")


if __name__ == "__main__":
    main()
