#!/usr/bin/env python3
"""Build the web derivative and poster frame for a self-hosted video.

WHY THIS EXISTS. The first Short in NATFISH in Motion was pulled by YouTube -
"blocked due to the claimed content by WMG" - so the embed rendered as a dead
"Video unavailable" panel on the live site. The client supplied the original
file to run from the site directly until the YouTube upload is sorted out.

THE AUDIO IS DROPPED BY DEFAULT. WMG claimed the music on the soundtrack, and
moving the file off YouTube does not move it out of that claim: hosting it on
natfish.bz is still publishing the track, with the co-operative as publisher
rather than YouTube. The picture is the co-operative's own; the music is not.

`--with-audio` keeps it anyway. The client asked for the soundtrack back for a
board presentation, knowing that, and it is their site and their call. It is
meant to come off again straight afterwards - see INTERNAL-NOTES.md - and the
one-line revert is to re-run this script without the flag and repackage.

Everything else here is ordinary web-video hygiene:

  faststart   moves the moov atom to the front of the file. Without it the
              browser has to fetch the whole thing before the first frame, and
              the source arrived with moov last.
  yuv420p     the only chroma layout every browser decodes.
  poster      a real frame, so the card is a photograph before anyone presses
              play rather than a black rectangle.

Usage:
    python3 tools/process-video.py <source.mp4> <stem> [poster-seconds] [--with-audio]
"""
import pathlib
import subprocess
import sys

import imageio_ffmpeg

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "video"

# Constant Rate Factor. 26 is visually clean at this frame size and keeps a
# 26-second clip near 3.5 MB, which is the budget a page that also carries the
# photography can spare.
CRF = "26"


def run(args):
    subprocess.run([imageio_ffmpeg.get_ffmpeg_exe(), "-hide_banner",
                    "-loglevel", "error", *args], check=True)


def main():
    args = [a for a in sys.argv[1:] if a != "--with-audio"]
    with_audio = "--with-audio" in sys.argv
    if not 2 <= len(args) <= 3:
        raise SystemExit(__doc__)
    src = pathlib.Path(args[0])
    stem = args[1]
    poster_at = args[2] if len(args) == 3 else "1"
    if not src.is_file():
        raise SystemExit(f"ERROR: {src} does not exist")
    OUT.mkdir(parents=True, exist_ok=True)

    mp4 = OUT / f"{stem}.mp4"
    # AAC at 128k rather than a straight copy: the source is 131k stereo, and
    # re-encoding keeps the muxer from carrying anything else across.
    audio = ["-c:a", "aac", "-b:a", "128k"] if with_audio else ["-an"]
    run(["-i", str(src), *audio, "-c:v", "libx264", "-profile:v", "main",
         "-pix_fmt", "yuv420p", "-crf", CRF, "-preset", "slow",
         "-movflags", "+faststart", str(mp4), "-y"])

    poster = OUT / f"{stem}-poster.jpg"
    run(["-ss", poster_at, "-i", str(src), "-frames:v", "1", "-q:v", "4",
         str(poster), "-y"])

    # The dimensions the markup has to declare so the card reserves the right
    # box before the file arrives.
    import re
    probe = subprocess.run(
        [imageio_ffmpeg.get_ffmpeg_exe(), "-hide_banner", "-i", str(mp4)],
        capture_output=True, text=True).stderr
    line = next(l for l in probe.splitlines() if "Video:" in l)
    # The frame size, not the codec tag: "avc1 / 0x31637661" also matches a
    # naive search for a digit followed by an x.
    w, h = re.search(r"\b(\d{2,5})x(\d{2,5})\b", line).groups()
    dims = f"{w}x{h}"

    dims_py = ROOT / "tools" / "video_dims.py"
    dims_py.write_text(
        "# Generated by tools/process-video.py. Do not edit by hand.\n"
        "VIDEO_DIMS = {\n"
        f'    "{stem}": ({w}, {h}),\n'
        "}\n", encoding="utf-8")

    # Check the output rather than trusting the flag, in both directions: a
    # silent regression either way is the failure that matters here.
    has_audio = "Audio:" in probe
    if has_audio != with_audio:
        raise SystemExit(
            "ERROR: asked for audio but the encode has none"
            if with_audio else
            "ERROR: the encode still carries an audio track")
    if with_audio:
        print("  !! SOUNDTRACK INCLUDED - temporary, see INTERNAL-NOTES.md")

    # A VP9 WebM was tried alongside this and came out at 6.95 MB against the
    # MP4's 3.69 for the same clip - handheld footage of moving water and
    # lobster shell is close to worst case for VP9 at a sane speed setting.
    # H.264 in MP4 plays in every browser that matters, so it ships alone.
    for f in (mp4, poster):
        print(f"  {f.relative_to(ROOT)}  {f.stat().st_size / 1024 / 1024:.2f} MB")
    print(f"  {dims}, {'with audio' if with_audio else 'no audio track'}")


if __name__ == "__main__":
    main()
