#!/usr/bin/env python3
"""Build the web derivatives for the three approved homepage hero images.

These three came from the original V1 image pack and were reviewed and approved
by the client for the homepage hero. They are kept in assets/img/concept/,
apart from assets/img/official/, because their provenance is different: the
official folder holds photographs the General Manager supplied of NATFISH's own
people and rooms, while these are illustrative sea-and-boat imagery from the
concept pack. Keeping the two apart in the path is what stops the distinction
being lost the next time someone reaches for an image.

Their alt text follows the same rule the client set for concept photography in
the original brief: describe only what is visible, and never assert that a
person, vessel or catch belongs to NATFISH.

Nothing is recoloured, retouched or crop-adjusted. The only operation is
downscaling to web sizes and stripping metadata.

Usage:
    python3 tools/process-hero-images.py <v1-image-pack-dir>
"""
import pathlib
import sys

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONCEPT = ROOT / "assets" / "img" / "concept"

# A hero fills the viewport width on a phone and 60% of it on a desktop, so it
# needs a larger top tier than the in-page photography does.
TIERS = (480, 800, 1400, 1920)

# Source file -> published name, in the approved carousel order. The client
# named the fisherwoman as the default first slide and her favourite of the
# three, so she leads and is the one that is preloaded.
HEROES = [
    ("natfish_image_03", "hero-1-fisher-with-conch-catch"),
    ("natfish_image_10", "hero-2-boat-leaving-harbour"),
    ("natfish_image_01", "hero-3-fishers-at-sunrise"),
]


def strip(im):
    """Return the pixels with no EXIF, ICC or other carried-over metadata."""
    clean = Image.new(im.mode, im.size)
    clean.putdata(list(im.getdata()))
    return clean


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    src_dir = pathlib.Path(sys.argv[1])
    CONCEPT.mkdir(parents=True, exist_ok=True)

    dims = {}
    for src, stem in HEROES:
        path = src_dir / f"{src}.jpg"
        if not path.exists():
            raise SystemExit(f"ERROR: missing source {path}")
        im = strip(Image.open(path).convert("RGB"))
        native = max(im.size)

        written = []
        for tier in TIERS:
            edge = min(tier, native)
            scale = edge / native
            size = (round(im.width * scale), round(im.height * scale))
            if size in written:
                continue
            r = im.resize(size, Image.LANCZOS)
            r.save(CONCEPT / f"{stem}-{tier}.webp", "WEBP", quality=82, method=6)
            r.save(CONCEPT / f"{stem}-{tier}.jpg", "JPEG", quality=84,
                   optimize=True, progressive=True)
            written.append(size)
        dims[stem] = written[-1]
        print(f"  {stem:34s} {im.width}x{im.height} -> "
              f"{', '.join(f'{w}x{h}' for w, h in written)}")

    lines = ["# Generated by tools/process-hero-images.py. Do not edit by hand.",
             "HERO_DIMS = {"]
    for stem, (w, h) in dims.items():
        lines.append(f'    "{stem}": ({w}, {h}),')
    lines.append("}")
    (ROOT / "tools" / "hero_dims.py").write_text("\n".join(lines) + "\n",
                                                 encoding="utf-8")

    total = sum(f.stat().st_size for f in CONCEPT.iterdir() if f.is_file())
    print(f"\nwrote {len(dims)} hero images, {total / 1024 / 1024:.2f} MB")


if __name__ == "__main__":
    main()
