#!/usr/bin/env python3
"""Build the web derivatives for the About page hero.

The client supplied one photograph of the NATFISH premises as a pre-cropped
responsive pair: a 1672x941 landscape frame for the desktop banner and a
941x1672 portrait frame for the phone. Both crops are the same photograph and
the client chose each framing, so neither is re-cropped here. They land in
assets/img/official/ with the rest of the client's own photography.

This is deliberately NOT tools/process-hero-images.py. That script rebuilds the
whole homepage carousel from source files which are not in this repository, so
running it to add one photograph would drop five heroes that are live. This
writes one pair and its own dimension table, and touches nothing else.

Nothing is recoloured, retouched or crop-adjusted. The only operations are
downscaling to web sizes and stripping metadata.

Usage:
    python3 tools/process-about-hero.py <dir containing the two PNGs>
"""
import pathlib
import sys

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
OFFICIAL = ROOT / "assets" / "img" / "official"

STEM = "about-facility"

# Widths, as a srcset `w` descriptor means. Neither list goes past its source:
# upscaling a 1672px photograph to 1920 would hand the browser a bigger file
# with no more detail in it, and the density calculation would believe it.
TIERS = {
    "desktop": (800, 1200, 1672),
    "mobile": (360, 540, 720, 941),
}


def derive(src, stem, tiers):
    im = Image.open(src)
    if im.mode != "RGB":
        im = im.convert("RGB")
    clean = Image.new("RGB", im.size)      # drops every metadata block
    clean.paste(im)
    written = []
    for w in tiers:
        if w > clean.width:
            continue
        h = round(clean.height * w / clean.width)
        out = clean.resize((w, h), Image.LANCZOS)
        out.save(OFFICIAL / f"{stem}-{w}.webp", "WEBP", quality=82, method=6)
        out.save(OFFICIAL / f"{stem}-{w}.jpg", "JPEG", quality=84,
                 optimize=True, progressive=True)
        written.append(w)
        print(f"  {stem}-{w}  {w}x{h}")
    return clean.size, tuple(written)


def main():
    src_dir = pathlib.Path(sys.argv[1])
    OFFICIAL.mkdir(parents=True, exist_ok=True)
    dims, tiers = {}, {}
    for crop in ("desktop", "mobile"):
        src = src_dir / f"{STEM}-{crop}.png"
        if not src.is_file():
            raise SystemExit(f"missing source: {src}")
        stem = f"{STEM}-{crop}"
        print(stem)
        dims[stem], tiers[stem] = derive(src, stem, TIERS[crop])

    out = ROOT / "tools" / "about_dims.py"
    lines = ["# Generated by tools/process-about-hero.py. Do not edit by hand.",
             "ABOUT_DIMS = {"]
    lines += [f'    "{k}": {v},' for k, v in dims.items()]
    lines += ["}", "",
              "# The tiers actually written. A source is never upscaled, so this is what",
              "# the srcset may list.", "ABOUT_TIERS = {"]
    lines += [f'    "{k}": {v},' for k, v in tiers.items()]
    lines += ["}", ""]
    out.write_text("\n".join(lines))
    print(f"\nwrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
