# Generated by tools/process-v2-images.py. Do not edit by hand.
DIMS = {
    "01-lobster-packing-team-wide": (1400, 876),
    "02-lobster-packing-line-portrait": (874, 1400),
    "03-lobster-processing-room-wide": (1400, 876),
    "04-fresh-conch-processing-closeup": (1400, 876),
    "05-lobster-tail-packing-boxes": (1053, 1400),
    "06-lobster-tail-packing-close": (1053, 1400),
    "07-lobster-washing-station": (1054, 1400),
    "08-lobster-weighing-and-sorting": (1054, 1400),
    "09-lobster-processing-table": (1054, 1400),
    "10-cold-storage-room": (788, 1400),
    "01-belizean-pride-lobster-cases": (1400, 920),
    "02-belizean-pride-orange-lobster-tails": (1254, 677),
    "03-belizean-pride-raw-lobster-tails": (1254, 602),
    "04-wild-caught-frozen-conch": (1400, 532),
}
